export enum NotificationTypeEnum {
    Info = "INFO",
    Contract = "CONTRACT",
    Training = "TRAINING",
    Warning = "WARNING",
    Termination = "TERMINATION",
    Reward = "REWARD",
    Assessment = "ASSESSMENT",
    Mission = "MISSION",
    Overtime = "OVERTIME",
    Leave = "LEAVE",
    Wage = "WAGE",
    UpdatePersonalInfo = "UPDATE_PERSONAL_INFO",
    SelfRegistration = "SELF_REGISTRATION",
    PayslipBatch = "PAYSLIP_BATCH",
    otherEarning = "OTHER_EARNING",
    otherDeduction = "OTHER_DEDUCTION",
}